//: #### Other pages
//:
//: * [Demo for `swiftgen colors`](Colors-Demo)
//: * [Demo for `swiftgen fonts`](Fonts-Demo)
//: * [Demo for `swiftgen ib`](InterfaceBuilder-Demo)
//: * Demo for `swiftgen json`
//: * [Demo for `swiftgen plist`](Plist-Demo)
//: * [Demo for `swiftgen strings`](Strings-Demo)
//: * [Demo for `swiftgen xcassets`](XCAssets-Demo)
//: * [Demo for `swiftgen yaml`](YAML-Demo)

// setup code
private final class BundleToken {}
bundle = Bundle(for: BundleToken.self)

//: #### Example of code generated by swiftgen json with "inline-swift4" template

import Foundation

// swiftlint:disable superfluous_disable_command
// swiftlint:disable file_length

// MARK: - JSON Files

// swiftlint:disable identifier_name line_length number_separator type_body_length
internal enum JSONFilesInline {
  internal enum Documents {
    internal enum Document1 {
      internal static let items: [String] = ["Mark McGwire", "Sammy Sosa", "Ken Griffey"]
    }
    internal enum Document2 {
      internal static let items: [String] = ["Chicago Cubs", "St Louis Cardinals"]
    }
  }
  internal enum GroceryList {
    internal static let items: [String] = ["value1", "value2"]
  }
  internal enum Json {
    internal static let key2: String = "2"
    internal static let key3: [String: Any] = ["nestedKey3": ["1", "2", "3"]]
    internal static let key4: Any? = nil
    internal static let key1: String = "value1"
  }
  internal enum Mapping {
    internal static let key2: Double = 1.0
    internal static let key3: [String: Any] = ["nestedKey1": "nestedValue1", "nestedKey2": "nestedValue2"]
    internal static let key4: Any? = nil
    internal static let key1: String = "value1"
  }
  internal enum Scalar {
    internal static let value: String = "value1"
  }
}
// swiftlint:enable identifier_name line_length number_separator type_body_length

//: #### Example of code generated by swiftgen json with "runtime-swift4" template

// swiftlint:disable superfluous_disable_command
// swiftlint:disable file_length

// MARK: - JSON Files

// swiftlint:disable identifier_name line_length type_body_length
internal enum JSONFilesRuntime {
  internal enum Json {
    private static let _document = JSONDocument(path: "json.json")
    internal static let key2: String = _document["key2"]
    internal static let key3: [String: Any] = _document["key3"]
    internal static let key4: Any? = _document["key4"]
    internal static let key1: String = _document["key1"]
  }
}
// swiftlint:enable identifier_name line_length type_body_length

//: #### Usage Example

// Access content embedded inline in Swift
let list = JSONFilesInline.GroceryList.items
let dictionary = JSONFilesInline.Mapping.key3
let name = JSONFilesInline.Scalar.value

// Or access content by loading JSON file at runtime
let stringValue = JSONFilesRuntime.Json.key1
let doubleValue = JSONFilesRuntime.Json.key2
let info = JSONFilesRuntime.Json.key3
