//: #### Other pages
//:
//: * [Demo for `swiftgen strings`](Strings-Demo)
//: * [Demo for `swiftgen images`](Images-Demo)
//: * [Demo for `swiftgen storyboards`](Storyboards-Demo)
//: * [Demo for `swiftgen colors`](Colors-Demo)
//: * [Demo for `swiftgen fonts`](Fonts-Demo)
//: * Demo for `swiftgen coredata model`
//: * [Demo for `swiftgen coredata mahine` and `swiftgen coredata human`](CoreData-Entity-Demo)


//: #### Example of code generated by `swiftgen coredata model`

// Generated using SwiftGen, by O.Halligon — https://github.com/AliSoftware/SwiftGen

import Foundation

// swiftlint:disable file_length
// swiftlint:disable type_body_length
// swiftlint:disable nesting
public struct CoreDataEntity {
   public struct Session {
      public static let name = "Session"

      public class Field {
         public static let sessionId = "sessionId"
         public static let user = "user"
      }
   }
   public struct User {
      public static let name = "User"

      public class Field {
         public static let about = "about"
         public static let email = "email"
         public static let fullName = "fullName"
         public static let userId = "userId"
         public static let userName = "userName"
         public static let session = "session"
      }
   }
}


//: #### Usage Example

import CoreData

let context = createContext()

let user = NSEntityDescription.insertNewObjectForEntityForName(CoreDataEntity.User.name, inManagedObjectContext: context)
user.setValue("John Doe", forKey: CoreDataEntity.User.Field.fullName)
user.setValue("john", forKey: CoreDataEntity.User.Field.userName)
