import Foundation

//: #### SwiftGenAssetsEnumFactory Usage Example

let factory = SwiftGenAssetsEnumFactory()

factory.addAssetName("Green-Apple")
factory.addAssetName("Red-Apple")
factory.addAssetName("Banana")
factory.addAssetName("Big_Pear")
factory.addAssetName("stop.button.enabled")

print(factory.generate())


//: #### Code Generated by the Factory

/*
enum ImageAsset : String {
    case GreenApple = "Green-Apple"
    case RedApple = "Red-Apple"
    case Banana = "Banana"
    case BigPear = "Big_Pear"
    case StopButtonEnabled = "stop.button.enabled"

    var image: UIImage {
        return UIImage(named: self.rawValue)!
    }
}

extension UIImage {
    convenience init(asset: ImageAsset) {
        self.init(named: asset.rawValue)!
    }
}
*/

//: #### Usage Example

// let image = UIImage(.GreenApple)


