//: #### Other pages
//:
//: * [Demo for `swiftgen strings`](Strings-Demo)
//: * Demo for `swiftgen images`
//: * [Demo for `swiftgen storyboards`](Storyboards-Demo)
//: * [Demo for `swiftgen colors`](Colors-Demo)
//: * [Demo for `swiftgen fonts`](Fonts-Demo)

//: #### Example of code generated by swiftgen-assets

// Generated using SwiftGen, by O.Halligon — https://github.com/AliSoftware/SwiftGen

import UIKit

enum Asset: String {
    case exoticBanana = "Exotic/Banana"
    case exoticMango = "Exotic/Mango"
    case lemon = "Lemon"
    case roundApricot = "Round/Apricot"
    case roundOrange = "Round/Orange"
    case roundApple = "Round/Apple"
    case roundDoubleCherry = "Round/Double/Cherry"
    case roundTomato = "Round/Tomato"

    var image: UIImage {
        return UIImage(asset: self)
    }
}

extension UIImage {
    convenience init!(asset: Asset) {
        self.init(named: asset.rawValue)
    }
}

//: #### Usage Example

let image = UIImage(asset: .exoticBanana)

Asset.roundTomato.image
