//: #### Other pages
//:
//: * [Demo for `swiftgen colors`](Colors-Demo)
//: * [Demo for `swiftgen fonts`](Fonts-Demo)
//: * [Demo for `swiftgen ib`](InterfaceBuilder-Demo)
//: * [Demo for `swiftgen json`](JSON-Demo)
//: * [Demo for `swiftgen plist`](Plist-Demo)
//: * [Demo for `swiftgen strings`](Strings-Demo)
//: * [Demo for `swiftgen xcassets`](XCAssets-Demo)
//: * Demo for `swiftgen yaml`

//: #### Example of code generated by swiftgen yaml with "inline-swift4" template

import Foundation

// swiftlint:disable superfluous_disable_command
// swiftlint:disable file_length

// MARK: - YAML Files

// swiftlint:disable identifier_name line_length number_separator type_body_length
internal enum YAMLFiles {
  internal enum Documents {
    internal enum Document1 {
      internal static let items: [String] = ["Mark McGwire", "Sammy Sosa", "Ken Griffey"]
    }
    internal enum Document2 {
      internal static let items: [String] = ["Chicago Cubs", "St Louis Cardinals"]
    }
  }
  internal enum GroceryList {
    internal static let items: [String] = ["value1", "value2"]
  }
  internal enum Json {
    internal static let key2: String = "2"
    internal static let key3: [String: Any] = ["nestedKey3": ["1", "2", "3"]]
    internal static let key4: Any? = nil
    internal static let key1: String = "value1"
  }
  internal enum Mapping {
    internal static let key2: Double = 1.0
    internal static let key3: [String: Any] = ["nestedKey1": "nestedValue1", "nestedKey2": "nestedValue2"]
    internal static let key4: Any? = nil
    internal static let key1: String = "value1"
  }
  internal enum Scalar {
    internal static let value: String = "value1"
  }
}
// swiftlint:enable identifier_name line_length number_separator type_body_length

//: #### Usage Example

// Access content embedded inline in Swift
let list = YAMLFiles.GroceryList.items
let dictionary = YAMLFiles.Mapping.key3
let name = YAMLFiles.Scalar.value
let documentItems = YAMLFiles.Documents.Document1.items
