//: #### Other pages
//:
//: * [Demo for `swiftgen colors`](Colors-Demo)
//: * [Demo for `swiftgen fonts`](Fonts-Demo)
//: * [Demo for `swiftgen ib`](InterfaceBuilder-Demo)
//: * [Demo for `swiftgen json`](JSON-Demo)
//: * Demo for `swiftgen plist`
//: * [Demo for `swiftgen strings`](Strings-Demo)
//: * [Demo for `swiftgen xcassets`](XCAssets-Demo)
//: * [Demo for `swiftgen yaml`](YAML-Demo)

// setup code
private final class BundleToken {}
bundle = Bundle(for: BundleToken.self)

//: #### Example of code generated by swiftgen plist with "inline-swift4" template

import Foundation

// swiftlint:disable superfluous_disable_command
// swiftlint:disable file_length

// MARK: - Plist Files

// swiftlint:disable identifier_name line_length number_separator type_body_length
internal enum PlistFilesInline {
  internal enum Info {
    internal static let cfBundleDevelopmentRegion: String = "en"
    internal static let cfBundleShortVersionString: String = "1.2.0"
    internal static let uiLaunchStoryboardName: String = "LaunchScreen"
    internal static let cfBundleInfoDictionaryVersion: String = "6.0"
    internal static let uiStatusBarStyle: String = "UIStatusBarStyleDefault"
    internal static let uiSupportedInterfaceOrientations: [String] = ["UIInterfaceOrientationPortrait", "UIInterfaceOrientationPortraitUpsideDown", "UIInterfaceOrientationLandscapeRight", "UIInterfaceOrientationLandscapeLeft"]
    internal static let uiMainStoryboardFile: String = "Start"
  }
  internal enum Array {
    internal static let items: [String] = ["value1", "value2"]
  }
  internal enum Dictionary {
    internal static let key2: [String: Any] = ["nestedKey2": "nestedValue2"]
    internal static let key1: String = "value1"
  }
}
// swiftlint:enable identifier_name line_length number_separator type_body_length

//: #### Example of code generated by swiftgen plist with "runtime-swift4" template

// swiftlint:disable superfluous_disable_command
// swiftlint:disable file_length

// MARK: - Plist Files

// swiftlint:disable identifier_name line_length type_body_length
internal enum PlistFilesRuntime {
  internal enum Info {
    private static let _document = PlistDocument(path: "TestInfo.plist")
    internal static let cfBundleDevelopmentRegion: String = _document["CFBundleDevelopmentRegion"]
    internal static let cfBundleShortVersionString: String = _document["CFBundleShortVersionString"]
    internal static let uiLaunchStoryboardName: String = _document["UILaunchStoryboardName"]
    internal static let cfBundleInfoDictionaryVersion: String = _document["CFBundleInfoDictionaryVersion"]
    internal static let uiStatusBarStyle: String = _document["UIStatusBarStyle"]
    internal static let uiSupportedInterfaceOrientations: [String] = _document["UISupportedInterfaceOrientations"]
    internal static let uiMainStoryboardFile: String = _document["UIMainStoryboardFile"]
  }
  internal enum Array {
    internal static let items: [String] = arrayFromPlist(at: "array.plist")
  }
  internal enum Dictionary {
    private static let _document = PlistDocument(path: "dictionary.plist")
    internal static let key2: [String: Any] = _document["key2"]
    internal static let key1: String = _document["key1"]
  }
}
// swiftlint:enable identifier_name line_length type_body_length

//: #### Usage Example

// Access content embedded inline in Swift
let region = PlistFilesInline.Info.cfBundleDevelopmentRegion
let orientations = PlistFilesInline.Info.uiSupportedInterfaceOrientations
let info = PlistFilesInline.Dictionary.key2

// Or access content by loading Plist files at runtime
let style = PlistFilesRuntime.Info.uiStatusBarStyle
let items = PlistFilesRuntime.Array.items
